# First step: Build with Node.js
FROM node:12 AS Builder
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm i install
COPY . /app

RUN npm run build

# Deliver the dist folder with Nginx
FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=Builder /app/dist /server_root/
COPY ./scripts/nginx_entrypoint.sh /

CMD ["/nginx_entrypoint.sh"]
