version: '3.5'

services:
  frontend:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
    restart: always
    command: npm run serve
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: "development"
      VUE_APP_GRAPHQL_ENDPOINT_URL: "ws://localhost:12040/graphql"
