# First step: Build with Node.js
FROM node:12 AS Builder
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm i install
COPY . /app
RUN npm run build

# Deliver the dist folder with Nginx
FROM nginx

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=Builder /app/dist /usr/share/nginx/html
COPY ./scripts/nginx_entrypoint.sh /

CMD ["/nginx_entrypoint.sh"]