/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class AbsoluteVote extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    parameters(
      arg0: string | number[]
    ): TransactionObject<{
      precReq: BN;
      voteOnBehalf: string;
      0: BN;
      1: string;
    }>;

    proposals(
      arg0: string | number[]
    ): TransactionObject<{
      organizationId: string;
      open: boolean;
      callbacks: string;
      numOfChoices: BN;
      paramsHash: string;
      totalVotes: BN;
      0: string;
      1: boolean;
      2: string;
      3: BN;
      4: string;
      5: BN;
    }>;

    organizations(arg0: string | number[]): TransactionObject<string>;

    getNumberOfChoices(_proposalId: string | number[]): TransactionObject<BN>;

    voteInfo(
      _proposalId: string | number[],
      _voter: string
    ): TransactionObject<{
      0: BN;
      1: BN;
    }>;

    voteStatus(
      _proposalId: string | number[],
      _choice: number | string
    ): TransactionObject<BN>;

    isVotable(_proposalId: string | number[]): TransactionObject<boolean>;

    getAllowedRangeOfChoices(): TransactionObject<{
      min: BN;
      max: BN;
      0: BN;
      1: BN;
    }>;

    getParametersHash(
      _precReq: number | string,
      _voteOnBehalf: string
    ): TransactionObject<string>;

    propose(
      _numOfChoices: number | string,
      _paramsHash: string | number[],
      arg2: string,
      _organization: string
    ): TransactionObject<string>;

    vote(
      _proposalId: string | number[],
      _vote: number | string,
      _amount: number | string,
      _voter: string
    ): TransactionObject<boolean>;

    cancelVote(_proposalId: string | number[]): TransactionObject<void>;

    execute(_proposalId: string | number[]): TransactionObject<boolean>;

    setParameters(
      _precReq: number | string,
      _voteOnBehalf: string
    ): TransactionObject<string>;

    proposalsCnt(): TransactionObject<BN>;
    MAX_NUM_OF_CHOICES(): TransactionObject<BN>;
    isAbstainAllow(): TransactionObject<boolean>;
  };
  events: {
    AVVoteProposal: ContractEvent<{
      _proposalId: string;
      _isProxyVote: boolean;
      0: string;
      1: boolean;
    }>;
    NewProposal: ContractEvent<{
      _proposalId: string;
      _organization: string;
      _numOfChoices: BN;
      _proposer: string;
      _paramsHash: string;
      0: string;
      1: string;
      2: BN;
      3: string;
      4: string;
    }>;
    ExecuteProposal: ContractEvent<{
      _proposalId: string;
      _organization: string;
      _decision: BN;
      _totalReputation: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
    }>;
    VoteProposal: ContractEvent<{
      _proposalId: string;
      _organization: string;
      _voter: string;
      _vote: BN;
      _reputation: BN;
      0: string;
      1: string;
      2: string;
      3: BN;
      4: BN;
    }>;
    CancelProposal: ContractEvent<{
      _proposalId: string;
      _organization: string;
      0: string;
      1: string;
    }>;
    CancelVoting: ContractEvent<{
      _proposalId: string;
      _organization: string;
      _voter: string;
      0: string;
      1: string;
      2: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
