/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class AccessControl extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    setCeo(newCeo: string): TransactionObject<void>;

    setCoo(newCoo: string): TransactionObject<void>;

    setCfo(newCfo: string): TransactionObject<void>;

    cfoAddress(): TransactionObject<string>;
    ceoAddress(): TransactionObject<string>;
    cooAddress(): TransactionObject<string>;
  };
  events: {
    CEOTransferred: ContractEvent<{
      previousCeo: string;
      newCeo: string;
      0: string;
      1: string;
    }>;
    COOTransferred: ContractEvent<{
      previousCoo: string;
      newCoo: string;
      0: string;
      1: string;
    }>;
    CFOTransferred: ContractEvent<{
      previousCfo: string;
      newCfo: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
