/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class AssetsRegistriesRegistry extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    getAssetsRegistryAddress(
      _hashedAssetRegistryId: string | number[]
    ): TransactionObject<string>;

    renounceOwnership(): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    setAssetsRegistryAddress(
      _hashedAssetRegistryId: string | number[],
      _assetRegistryAddress: string
    ): TransactionObject<boolean>;

    owner(): TransactionObject<string>;
    isOwner(): TransactionObject<boolean>;
  };
  events: {
    AssetsRegistryUpdated: ContractEvent<{
      hashedAssetRegistryId: string;
      updatedAddress: string;
      0: string;
      1: string;
    }>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
