/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class AssetWallet extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    onERC721Received(
      _operator: string,
      _from: string,
      _tokenId: number | string,
      _data: string | number[]
    ): TransactionObject<string>;

    genericCall(
      _to: string,
      _gas: number | string,
      _value: number | string,
      _encodedFunction: string | number[]
    ): TransactionObject<boolean>;

    assetOwned(): TransactionObject<BN>;
    assetWalletFactory(): TransactionObject<string>;
  };
  events: {
    GenericCallSuccess: ContractEvent<{
      result: string;
      success: boolean;
      0: string;
      1: boolean;
    }>;
    ReceivedEth: ContractEvent<{
      sender: string;
      amount: BN;
      0: string;
      1: BN;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
