/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class BadERC20 extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    balances(arg0: string): TransactionObject<BN>;

    allowance(arg0: string, arg1: string): TransactionObject<BN>;

    transfer(_to: string, _value: number | string): TransactionObject<void>;

    transferFrom(
      arg0: string,
      _to: string,
      _value: number | string
    ): TransactionObject<void>;

    approve(_spender: string, _value: number | string): TransactionObject<void>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
