/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class Debug extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {};
  events: {
    LogAddress: ContractEvent<string>;
    LogInt: ContractEvent<BN>;
    LogString: ContractEvent<string>;
    LogUint: ContractEvent<BN>;
    LogBytes: ContractEvent<string>;
    LogBytes32: ContractEvent<string>;
    LogBool: ContractEvent<boolean>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
