/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class FixedReputationAllocation extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    beneficiaries(arg0: string): TransactionObject<boolean>;

    renounceOwnership(): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    initialize(
      _avatar: string,
      _reputationReward: number | string,
      _redeemEnableTime: number | string
    ): TransactionObject<void>;

    redeem(_beneficiary: string): TransactionObject<boolean>;

    addBeneficiary(_beneficiary: string): TransactionObject<void>;

    addBeneficiaries(_beneficiaries: (string)[]): TransactionObject<void>;

    enable(): TransactionObject<void>;

    numberOfBeneficiaries(): TransactionObject<BN>;
    redeemEnableTime(): TransactionObject<BN>;
    isEnable(): TransactionObject<boolean>;
    avatar(): TransactionObject<string>;
    owner(): TransactionObject<string>;
    isOwner(): TransactionObject<boolean>;
    beneficiaryReward(): TransactionObject<BN>;
    reputationReward(): TransactionObject<BN>;
  };
  events: {
    Redeem: ContractEvent<{
      _beneficiary: string;
      _amount: BN;
      0: string;
      1: BN;
    }>;
    BeneficiaryAddressAdded: ContractEvent<string>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
