/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class GenericScheme extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    parameters(
      arg0: string | number[]
    ): TransactionObject<{
      intVote: string;
      voteParams: string;
      contractToCall: string;
      0: string;
      1: string;
      2: string;
    }>;

    organizationsProposals(
      arg0: string,
      arg1: string | number[]
    ): TransactionObject<{
      callData: string;
      value: BN;
      exist: boolean;
      passed: boolean;
      0: string;
      1: BN;
      2: boolean;
      3: boolean;
    }>;

    proposalsInfo(
      arg0: string,
      arg1: string | number[]
    ): TransactionObject<{
      blockNumber: BN;
      avatar: string;
      0: BN;
      1: string;
    }>;

    balanceOfStakingToken(
      _stakingToken: string,
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    reputationOf(
      _owner: string,
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    getTotalReputationSupply(
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    getParametersHash(
      _voteParams: string | number[],
      _intVote: string,
      _contractToCall: string
    ): TransactionObject<string>;

    getContractToCall(_avatar: string): TransactionObject<string>;

    stakingTokenTransfer(
      _stakingToken: string,
      _beneficiary: string,
      _amount: number | string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    mintReputation(
      _amount: number | string,
      _beneficiary: string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    burnReputation(
      _amount: number | string,
      _beneficiary: string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    executeProposal(
      _proposalId: string | number[],
      _decision: number | string
    ): TransactionObject<boolean>;

    execute(
      _avatar: string,
      _proposalId: string | number[]
    ): TransactionObject<void>;

    setParameters(
      _voteParams: string | number[],
      _intVote: string,
      _contractToCall: string
    ): TransactionObject<string>;

    proposeCall(
      _avatar: string,
      _callData: string | number[],
      _value: number | string,
      _descriptionHash: string
    ): TransactionObject<string>;
  };
  events: {
    NewCallProposal: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _callData: string;
      _value: BN;
      _descriptionHash: string;
      0: string;
      1: string;
      2: string;
      3: BN;
      4: string;
    }>;
    ProposalExecuted: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _genericCallReturnValue: string;
      0: string;
      1: string;
      2: string;
    }>;
    ProposalExecutedByVotingMachine: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _param: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    ProposalDeleted: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
