/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class GlobalConstraintRegistrar extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    parameters(
      arg0: string | number[]
    ): TransactionObject<{
      voteRegisterParams: string;
      intVote: string;
      0: string;
      1: string;
    }>;

    organizationsProposals(
      arg0: string,
      arg1: string | number[]
    ): TransactionObject<{
      gc: string;
      addGC: boolean;
      params: string;
      voteToRemoveParams: string;
      0: string;
      1: boolean;
      2: string;
      3: string;
    }>;

    proposalsInfo(
      arg0: string,
      arg1: string | number[]
    ): TransactionObject<{
      blockNumber: BN;
      avatar: string;
      0: BN;
      1: string;
    }>;

    balanceOfStakingToken(
      _stakingToken: string,
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    reputationOf(
      _owner: string,
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    voteToRemoveParams(arg0: string, arg1: string): TransactionObject<string>;

    getTotalReputationSupply(
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    getParametersHash(
      _voteRegisterParams: string | number[],
      _intVote: string
    ): TransactionObject<string>;

    stakingTokenTransfer(
      _stakingToken: string,
      _beneficiary: string,
      _amount: number | string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    mintReputation(
      _amount: number | string,
      _beneficiary: string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    burnReputation(
      _amount: number | string,
      _beneficiary: string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    executeProposal(
      _proposalId: string | number[],
      _param: number | string
    ): TransactionObject<boolean>;

    setParameters(
      _voteRegisterParams: string | number[],
      _intVote: string
    ): TransactionObject<string>;

    proposeGlobalConstraint(
      _avatar: string,
      _gc: string,
      _params: string | number[],
      _voteToRemoveParams: string | number[],
      _descriptionHash: string
    ): TransactionObject<string>;

    proposeToRemoveGC(
      _avatar: string,
      _gc: string,
      _descriptionHash: string
    ): TransactionObject<string>;
  };
  events: {
    NewGlobalConstraintsProposal: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _intVoteInterface: string;
      _gc: string;
      _params: string;
      _voteToRemoveParams: string;
      _descriptionHash: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
    }>;
    RemoveGlobalConstraintsProposal: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _intVoteInterface: string;
      _gc: string;
      _descriptionHash: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;
    ProposalExecuted: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _param: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    ProposalDeleted: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
