/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class Locking4Reputation extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    scores(arg0: string): TransactionObject<BN>;

    lockers(
      arg0: string,
      arg1: string | number[]
    ): TransactionObject<{
      amount: BN;
      releaseTime: BN;
      0: BN;
      1: BN;
    }>;

    redeem(_beneficiary: string): TransactionObject<BN>;

    redeemEnableTime(): TransactionObject<BN>;
    lockingStartTime(): TransactionObject<BN>;
    totalLocked(): TransactionObject<BN>;
    avatar(): TransactionObject<string>;
    getAgreementHash(): TransactionObject<string>;
    lockingEndTime(): TransactionObject<BN>;
    reputationRewardLeft(): TransactionObject<BN>;
    maxLockingPeriod(): TransactionObject<BN>;
    totalScore(): TransactionObject<BN>;
    lockingsCounter(): TransactionObject<BN>;
    totalLockedLeft(): TransactionObject<BN>;
    reputationReward(): TransactionObject<BN>;
  };
  events: {
    Redeem: ContractEvent<{
      _beneficiary: string;
      _amount: BN;
      0: string;
      1: BN;
    }>;
    Release: ContractEvent<{
      _lockingId: string;
      _beneficiary: string;
      _amount: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    Lock: ContractEvent<{
      _locker: string;
      _lockingId: string;
      _amount: BN;
      _period: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
