/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class SafeERC20Mock extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    transfer(_to: string, _value: number | string): TransactionObject<boolean>;

    transferWithFix(
      _to: string,
      _value: number | string
    ): TransactionObject<boolean>;

    transferFromWithFix(
      _from: string,
      _to: string,
      _value: number | string
    ): TransactionObject<boolean>;

    approveWithFix(
      _spender: string,
      _value: number | string
    ): TransactionObject<boolean>;

    token(): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
