/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class SignalScheme extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    proposals(
      arg0: string | number[]
    ): TransactionObject<{
      descriptionHash: string;
      executed: boolean;
      0: string;
      1: boolean;
    }>;

    proposalsInfo(
      arg0: string,
      arg1: string | number[]
    ): TransactionObject<{
      blockNumber: BN;
      avatar: string;
      0: BN;
      1: string;
    }>;

    balanceOfStakingToken(
      _stakingToken: string,
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    reputationOf(
      _owner: string,
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    getTotalReputationSupply(
      _proposalId: string | number[]
    ): TransactionObject<BN>;

    params(): TransactionObject<{
      voteApproveParams: string;
      intVote: string;
      signalType: BN;
      avatar: string;
      0: string;
      1: string;
      2: BN;
      3: string;
    }>;

    stakingTokenTransfer(
      _stakingToken: string,
      _beneficiary: string,
      _amount: number | string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    mintReputation(
      _amount: number | string,
      _beneficiary: string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    burnReputation(
      _amount: number | string,
      _beneficiary: string,
      _proposalId: string | number[]
    ): TransactionObject<boolean>;

    initialize(
      _avatar: string,
      _signalType: number | string,
      _voteApproveParams: string | number[],
      _intVote: string
    ): TransactionObject<void>;

    proposeSignal(_descriptionHash: string): TransactionObject<string>;

    executeProposal(
      _proposalId: string | number[],
      _param: number | string
    ): TransactionObject<boolean>;
  };
  events: {
    NewSignalProposal: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _signalType: BN;
      _descriptionHash: string;
      0: string;
      1: string;
      2: BN;
      3: string;
    }>;
    Signal: ContractEvent<{
      _avatar: string;
      _proposalId: string;
      _signalType: BN;
      _descriptionHash: string;
      0: string;
      1: string;
      2: BN;
      3: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
