/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class TokenCapGC extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    parameters(
      arg0: string | number[]
    ): TransactionObject<{
      token: string;
      cap: BN;
      0: string;
      1: BN;
    }>;

    getParametersHash(
      _token: string,
      _cap: number | string
    ): TransactionObject<string>;

    pre(
      arg0: string,
      arg1: string | number[],
      arg2: string | number[]
    ): TransactionObject<boolean>;

    post(
      arg0: string,
      _paramsHash: string | number[],
      arg2: string | number[]
    ): TransactionObject<boolean>;

    setParameters(
      _token: string,
      _cap: number | string
    ): TransactionObject<string>;

    when(): TransactionObject<BN>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
