/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class UniversalSchemeMock extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    genericCall(
      _avatar: string,
      _contract: string,
      _a: number | string,
      _b: string,
      _c: string | number[],
      _value: number | string
    ): TransactionObject<{
      0: boolean;
      1: string;
    }>;

    genericCallDirect(
      _avatar: string,
      _contract: string,
      _a: number | string,
      _b: string,
      _c: string | number[],
      _value: number | string
    ): TransactionObject<{
      0: boolean;
      1: string;
    }>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
