/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class WizardWallet extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    voteProposal(_vote: number | string): TransactionObject<BN>;

    withdrawEthFunds(): TransactionObject<void>;

    transferERC20(
      _erc20Address: string,
      _recipient: string,
      _amount: number | string
    ): TransactionObject<void>;

    transfer(
      _erc20Address: string,
      _recipient: string,
      _amount: number | string
    ): TransactionObject<void>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
