/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class WizardWalletFactory extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    wizardsWallets(arg0: number | string): TransactionObject<string>;

    createWallet(_wizardId: number | string): TransactionObject<void>;

    wizardsERC721AddressesProvider(): TransactionObject<string>;
  };
  events: {
    WizardWalletCreated: ContractEvent<{
      wizardId: BN;
      wizardWallet: string;
      0: BN;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
