/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class WizardGuildInterface extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    supportsInterface(
      interfaceId: string | number[]
    ): TransactionObject<boolean>;

    getApproved(tokenId: number | string): TransactionObject<string>;

    ownerOf(tokenId: number | string): TransactionObject<string>;

    balanceOf(owner: string): TransactionObject<BN>;

    isApprovedForAll(
      owner: string,
      operator: string
    ): TransactionObject<boolean>;

    getWizard(
      id: number | string
    ): TransactionObject<{
      owner: string;
      innatePower: BN;
      affinity: BN;
      metadata: string;
      0: string;
      1: BN;
      2: BN;
      3: string;
    }>;

    isApprovedOrOwner(
      spender: string,
      tokenId: number | string
    ): TransactionObject<boolean>;

    verifySignature(
      wizardId: number | string,
      hash: string | number[],
      sig: string | number[]
    ): TransactionObject<void>;

    verifySignatures(
      wizardId1: number | string,
      wizardId2: number | string,
      hash1: string | number[],
      hash2: string | number[],
      sig1: string | number[],
      sig2: string | number[]
    ): TransactionObject<void>;

    approve(to: string, tokenId: number | string): TransactionObject<void>;

    transferFrom(
      from: string,
      to: string,
      tokenId: number | string
    ): TransactionObject<void>;

    safeTransferFrom(
      from: string,
      to: string,
      tokenId: number | string
    ): TransactionObject<void>;

    setApprovalForAll(
      operator: string,
      _approved: boolean
    ): TransactionObject<void>;

    setAffinity(
      wizardId: number | string,
      newAffinity: number | string
    ): TransactionObject<void>;

    mintWizards(
      powers: (number | string)[],
      affinities: (number | string)[],
      owner: string
    ): TransactionObject<(BN)[]>;

    mintReservedWizards(
      wizardIds: (number | string)[],
      powers: (number | string)[],
      affinities: (number | string)[],
      owner: string
    ): TransactionObject<void>;

    setMetadata(
      wizardIds: (number | string)[],
      metadata: (string | number[])[]
    ): TransactionObject<void>;
  };
  events: {
    Transfer: ContractEvent<{
      from: string;
      to: string;
      tokenId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    Approval: ContractEvent<{
      owner: string;
      approved: string;
      tokenId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    ApprovalForAll: ContractEvent<{
      owner: string;
      operator: string;
      approved: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
