/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import {Contract, ContractOptions, EventOptions} from "web3-eth-contract";
import {EventLog} from "web3-core";
import {EventEmitter} from "events";
import {Callback, TransactionObject, ContractEvent} from "./types";

export class WizardNFT extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    wizardsById(
      arg0: number | string
    ): TransactionObject<{
      affinity: BN;
      innatePower: BN;
      owner: string;
      metadata: string;
      0: BN;
      1: BN;
      2: string;
      3: string;
    }>;

    supportsInterface(
      interfaceId: string | number[]
    ): TransactionObject<boolean>;

    balanceOf(owner: string): TransactionObject<BN>;

    ownerOf(wizardId: number | string): TransactionObject<string>;

    getApproved(wizardId: number | string): TransactionObject<string>;

    isApprovedForAll(
      owner: string,
      operator: string
    ): TransactionObject<boolean>;

    approve(to: string, wizardId: number | string): TransactionObject<void>;

    setApprovalForAll(to: string, approved: boolean): TransactionObject<void>;

    transferFrom(
      from: string,
      to: string,
      wizardId: number | string
    ): TransactionObject<void>;

    safeTransferFrom(
      from: string,
      to: string,
      wizardId: number | string
    ): TransactionObject<void>;
  };
  events: {
    Transfer: ContractEvent<{
      from: string;
      to: string;
      wizardId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    Approval: ContractEvent<{
      owner: string;
      approved: string;
      wizardId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    ApprovalForAll: ContractEvent<{
      owner: string;
      operator: string;
      approved: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;
    WizardConjured: ContractEvent<{
      wizardId: BN;
      affinity: BN;
      innatePower: BN;
      0: BN;
      1: BN;
      2: BN;
    }>;
    WizardAffinityAssigned: ContractEvent<{
      wizardId: BN;
      affinity: BN;
      0: BN;
      1: BN;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
