version: '3.5'

volumes:
  redis_data:
    driver: local

networks:
  overlay:
  traefik:
    external: true

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-prod
      args:
        VUE_APP_GRAPHQL_ENDPOINT_URL: "wss://cheezedao.com/graphql"
        VUE_APP_ETH_NETWORK: "rinkeby"
    networks:
      - overlay
      - traefik
    labels:
      traefik.frontend.rule: "Host:next.cheezedao.com,www.next.cheezedao.com"
      traefik.frontend.redirect.regex: "^https?://www.next.cheezedao.com/(.*)"
      traefik.frontend.redirect.replacement: "https://next.cheezedao.com/$${1}"
      traefik.port: '80'

  api:
    build:
      context: ./contracts
    restart: always
    networks:
      - overlay
    environment:
      ETH_NETWORK: "rinkeby"
      # GANACHE
      GANACHE_URL: "http://ganache:8545"
      URL_ETHEREUM_HTTP_PROVIDER_DEVELOPMENT: "http://ganache:8545"
      URL_ETHEREUM_WS_PROVIDER_DEVELOPMENT: "wss://ganache:8545"
      # RINKEBY
      MNEMONIC_TRUFFLE_RINKEBY: ""
      PK_TRUFFLE_RINKEBY: ""
      HDWALLET_ADDRESS_RINKEBY: ""
      URL_ETHEREUM_HTTP_PROVIDER_RINKEBY: "https://rinkeby.infura.io/v3/3f9d1321a68b41a092b3b4e404d3e537"
      URL_ETHEREUM_WS_PROVIDER_RINKEBY: "https://rinkeby.infura.io/v3/3f9d1321a68b41a092b3b4e404d3e537"
      # KOVAN
      MNEMONIC_TRUFFLE_KOVAN: ""
      PK_TRUFFLE_KOVAN: ""
      HDWALLET_ADDRESS_KOVAN: ""
      URL_ETHEREUM_HTTP_PROVIDER_KOVAN: "https://kovan.infura.io/v3/3f9d1321a68b41a092b3b4e404d3e537"
      URL_ETHEREUM_WS_PROVIDER_KOVAN: "wss://kovan.infura.io/v3/3f9d1321a68b41a092b3b4e404d3e537"

  redis:
    image: redis:latest
    networks:
      - overlay
    volumes:
      - type: volume
        source: redis_data
        target: /data
