version: '3.5'

services:
  contracts-env:
    depends_on:
      - ganache
    build:
      context: ./
    volumes:
      - ./:/src
    restart: always
    command: npm run sys:start-dev-container
    environment:
      TARGET: "development"
      MNEMONIC_TRUFFLE_KOVAN: ""
      PK_TRUFFLE_KOVAN: ""
      MNEMONIC_TRUFFLE_MAIN: ""
      PK_TRUFFLE_MAIN: ""
      HDWALLET_ADDRESS_KOVAN: ""
      HDWALLET_ADDRESS_MAIN: ""
      URL_ETHEREUM_HTTP_PROVIDER: ""
      URL_ETHEREUM_WS_PROVIDER: ""
      GANACHE_URL: "http://ganache:8545"
  
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: ["ganache-cli", "--gasLimit", "8000000"] #,"--blockTime", "1"]  
  
  thegraph-node:
    image: graphprotocol/graph-node:v0.14.0
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: mynicepassword
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: development:http://ganache:8545
      GRAPH_IPFS_TIMEOUT: '2'
      GRAPH_MAX_IPFS_FILE_BYTES: '102400'

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mynicepassword
      POSTGRES_USER: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/