/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AbsoluteVote"): TruffleContracts.AbsoluteVoteContract;
      require(name: "AccessControl"): TruffleContracts.AccessControlContract;
      require(
        name: "AssetsRegistriesRegistry"
      ): TruffleContracts.AssetsRegistriesRegistryContract;
      require(name: "AssetWallet"): TruffleContracts.AssetWalletContract;
      require(
        name: "AssetWalletFactory"
      ): TruffleContracts.AssetWalletFactoryContract;
      require(name: "Avatar"): TruffleContracts.AvatarContract;
      require(
        name: "ContributionReward"
      ): TruffleContracts.ContributionRewardContract;
      require(name: "Controller"): TruffleContracts.ControllerContract;
      require(
        name: "ControllerCreator"
      ): TruffleContracts.ControllerCreatorContract;
      require(
        name: "ControllerInterface"
      ): TruffleContracts.ControllerInterfaceContract;
      require(name: "DaoCreator"): TruffleContracts.DaoCreatorContract;
      require(name: "DAOToken"): TruffleContracts.DAOTokenContract;
      require(name: "ERC165"): TruffleContracts.ERC165Contract;
      require(name: "ERC1654"): TruffleContracts.ERC1654Contract;
      require(
        name: "ERC165Interface"
      ): TruffleContracts.ERC165InterfaceContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Burnable"): TruffleContracts.ERC20BurnableContract;
      require(
        name: "ERC721Receivable"
      ): TruffleContracts.ERC721ReceivableContract;
      require(
        name: "ERC721ReceiverDraft"
      ): TruffleContracts.ERC721ReceiverDraftContract;
      require(
        name: "ERC721ReceiverFinal"
      ): TruffleContracts.ERC721ReceiverFinalContract;
      require(name: "GenericScheme"): TruffleContracts.GenericSchemeContract;
      require(
        name: "GenesisProtocol"
      ): TruffleContracts.GenesisProtocolContract;
      require(
        name: "GenesisProtocolLogic"
      ): TruffleContracts.GenesisProtocolLogicContract;
      require(
        name: "GlobalConstraintInterface"
      ): TruffleContracts.GlobalConstraintInterfaceContract;
      require(
        name: "GlobalConstraintRegistrar"
      ): TruffleContracts.GlobalConstraintRegistrarContract;
      require(
        name: "IAssetsRegistriesRegistry"
      ): TruffleContracts.IAssetsRegistriesRegistryContract;
      require(name: "IERC165"): TruffleContracts.IERC165Contract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IERC721"): TruffleContracts.IERC721Contract;
      require(
        name: "IERC721Receiver"
      ): TruffleContracts.IERC721ReceiverContract;
      require(
        name: "IntVoteInterface"
      ): TruffleContracts.IntVoteInterfaceContract;
      require(name: "IOwnedAsset"): TruffleContracts.IOwnedAssetContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(
        name: "ProposalExecuteInterface"
      ): TruffleContracts.ProposalExecuteInterfaceContract;
      require(name: "QuorumVote"): TruffleContracts.QuorumVoteContract;
      require(name: "Reputation"): TruffleContracts.ReputationContract;
      require(
        name: "SchemeRegistrar"
      ): TruffleContracts.SchemeRegistrarContract;
      require(name: "TestContract"): TruffleContracts.TestContractContract;
      require(name: "UController"): TruffleContracts.UControllerContract;
      require(name: "UpgradeScheme"): TruffleContracts.UpgradeSchemeContract;
      require(
        name: "VotingMachineCallbacks"
      ): TruffleContracts.VotingMachineCallbacksContract;
      require(
        name: "VotingMachineCallbacksInterface"
      ): TruffleContracts.VotingMachineCallbacksInterfaceContract;
      require(name: "WizardGuild"): TruffleContracts.WizardGuildContract;
      require(
        name: "WizardGuildInterface"
      ): TruffleContracts.WizardGuildInterfaceContract;
      require(name: "WizardNFT"): TruffleContracts.WizardNFTContract;
      require(name: "WizardPresale"): TruffleContracts.WizardPresaleContract;
      require(
        name: "WizardPresaleInterface"
      ): TruffleContracts.WizardPresaleInterfaceContract;
      require(
        name: "WizardPresaleNFT"
      ): TruffleContracts.WizardPresaleNFTContract;
    }
  }
}
