version: '3.5'

networks:
  overlay:

volumes:
  redis_data:
    driver: local

x-contract-base: &contract-base
  image: node:12
  working_dir: /src
  restart: always
  volumes:
    - ./:/src
  networks:
    - overlay
  environment:
    # GANACHE
    GANACHE_URL: "http://ganache:8545"
    # RINKEBY
    MNEMONIC_TRUFFLE_RINKEBY: ""
    PK_TRUFFLE_RINKEBY: ""
    HDWALLET_ADDRESS_RINKEBY: ""
    URL_ETHEREUM_HTTP_PROVIDER_RINKEBY: ""
    URL_ETHEREUM_WS_PROVIDER_RINKEBY: ""
    # KOVAN
    MNEMONIC_TRUFFLE_KOVAN: ""
    PK_TRUFFLE_KOVAN: ""
    HDWALLET_ADDRESS_KOVAN: ""
    URL_ETHEREUM_HTTP_PROVIDER_KOVAN: ""
    URL_ETHEREUM_WS_PROVIDER_KOVAN: ""
    API_ETHEREUM_NETWORK_WS_URL: "wss://ws.kovan-node.ethlend.io"


services:
  contracts-env:
    <<: *contract-base
    command: npm run sys:start-dev-container

  contracts-api:
    <<: *contract-base
    command: npm run sys:start-api-server
    ports:
      - "12040:12040"

  ganache:
    image: trufflesuite/ganache-cli
    command: ["ganache-cli", "--gasLimit", "8000000"] #,"--blockTime", "1"]
    networks:
      - overlay
    ports:
      - "8545:8545"


  redis:
    image: redis:latest
    networks:
      - overlay
    volumes:
      - type: volume
        source: redis_data
        target: /data
